name: "Ingest ArXiv Papers"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: research_aggregator/ingest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run arXiv fetcher
        working-directory: research_aggregator/ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python arxiv_fetcher.py --max_results 20
